In [1]:
import numpy as np
import pandas as pd

Raumtypen

In [11]:
#import Raumtypen

#columnNames=['gemeindeId',"gem","wohngeb_insgesamt","wohngeb_1","wohngeb_2","wohngeb_3","wohnheime","wohnfläche",
#           "wohn_insgesamt","wohn_1raum","wohn_2raum","wohn_3raum","wohn_4raum","wohn_5raum","wohn_6raum","wohn_7raum","wohn_gr7raum","Unnamed: 17","ags"]

renameDict={'8-stellige AGS':'ags','gem':'id','gemname':'gem'}
             
raumtypen = pd.read_csv('data/Raumtypen.csv',sep=';',header=0,encoding="utf8")

#drop empty column
raumtypen.drop(columns=["Unnamed: 9","Unnamed: 10"],inplace=True)

raumtypen.rename(columns=renameDict,inplace=True)


#put ags as second column
raumtypen=raumtypen[['id','ags','gem','RegioStaR7','gemrs', 'gembev', 'gemfl', 'vbg', 'vbgrs', 'vbgname']]

#drop last 12 columns which are comments
#Einwohner.drop([i+13908 for i in range(33)],axis=0,inplace=True)

#change cell types to string, int or float defined as in dtypes dict
dtypesDict={'id':'string','ags':'string','gem':'string','RegioStaR7':'int','gemrs':'int64', 'gembev':'int', 'gemfl':'float', 'vbg':'int', 'vbgrs':'int', 'vbgname':'string'}
    
#change data types
for key in dtypesDict:
    #print(key)
    raumtypen[key]=raumtypen[key].astype(dtypesDict[key])
    
#make ags column 8 digits
for i in range(len(raumtypen['ags'])):
    if len(raumtypen.iat[i,1]) < 8 :
        raumtypen.iat[i,1]= '0'+ raumtypen.iat[i,1]

#print(raumtypen.dtypes)  

display(raumtypen)
raumtypen.to_pickle('data/Raumtypen.pki')

,id,ags,gem,RegioStaR7,gemrs,gembev,gemfl,vbg,vbgrs,vbgname
0,1001000,01001000,Flensburg,75,10010000000,89504,56.73,1001000,10010000,Flensburg
1,1002000,01002000,Kiel,72,10020000000,247548,118.65,1002000,10020000,Kiel
2,1003000,01003000,Lübeck,72,10030000000,217198,214.19,1003000,10030000,Lübeck
3,1004000,01004000,Neumünster,75,10040000000,79487,71.66,1004000,10040000,Neumünster
4,1051001,01051001,Albersdorf,77,10515175001,3670,17.12,1051975,10515175,Mitteldithmarschen
...,...,...,...,...,...,...,...,...,...,...
11082,16077047,16077047,Thonhausen,77,160775000000,537,9.42,16077909,160775009,Oberes Sprottental
11083,16077048,16077048,Treben,77,160775000000,1197,10.00,16077904,160775004,Pleißenaue
11084,16077049,16077049,Vollmershain,77,160775000000,317,5.06,16077909,160775009,Oberes Sprottental
11085,16077051,16077051,Wildenbörten,77,160775000000,252,7.82,16077909,160775009,Oberes Sprottental
11086,16077052,16077052,Windischleuba,77,160775000000,1925,20.73,16077904,160775004,Pleißenaue

In [142]:


def get_raumtyp(inVal,output='RegioStaR7',inputType='ags'):
    pop=raumtypen[raumtypen[inputType]==inVal][output]
    return pop.values[0]

In [143]:
get_raumtyp('01002000')

72

In [145]:
get_raumtyp('01002000','gem')

'Kiel'

Wohnungen

In [10]:
#import Wohnungen
columnNames=['id',"gem","wohngeb_insgesamt","wohngeb_1","wohngeb_2","wohngeb_3","wohnheime","wohnfläche",
           "wohn_insgesamt","wohn_1raum","wohn_2raum","wohn_3raum","wohn_4raum","wohn_5raum","wohn_6raum","wohn_7raum","wohn_gr7raum","Unnamed: 17","ags"]


Wohnungen = pd.read_csv('data/Wohnungen.csv',names=columnNames,sep=';',header=6,encoding="utf8")

#drop empty column
Wohnungen.drop(columns=["Unnamed: 17"],inplace=True)

#put ags as second column
Wohnungen=Wohnungen[['id','ags',"gem","wohngeb_insgesamt","wohngeb_1","wohngeb_2","wohngeb_3","wohnheime","wohnfläche",
           "wohn_insgesamt","wohn_1raum","wohn_2raum","wohn_3raum","wohn_4raum","wohn_5raum","wohn_6raum","wohn_7raum","wohn_gr7raum"]]

#drop last 12 columns which are comments
Wohnungen.drop([i+13908 for i in range(12)],axis=0,inplace=True)

#change cell types to string, int or float defined as in dtypes dict
   
dtypesDict={'id':'string',"gem":'string',"wohngeb_insgesamt":'int',"wohngeb_1":'int',"wohngeb_2":'int',"wohngeb_3":'int',"wohnheime":'int',"wohnfläche":'float',
            "wohn_insgesamt":'int',"wohn_1raum":'int',"wohn_2raum":'int',"wohn_3raum":'int',"wohn_4raum":'int',"wohn_5raum":'int',"wohn_6raum":'int',"wohn_7raum":'int',"wohn_gr7raum":'int',"ags":'string'}

#workaround for missing values replace all '-' with -1 
Wohnungen.replace('-',-1,inplace=True)
#change data types
for key in dtypesDict:
    Wohnungen[key]=Wohnungen[key].astype(dtypesDict[key])
#and replace all -1 with NaN   
Wohnungen.replace(-1,np.NaN,inplace=True)

#make ags column 8 digits
for i in range(len(Wohnungen['ags'])):
    if len(Wohnungen.iat[i,1]) < 8 :
        Wohnungen.iat[i,1]= '0'+ Wohnungen.iat[i,1]
        
display(Wohnungen)
Wohnungen.to_pickle('data/Wohnungen.pki')

,id,ags,gem,wohngeb_insgesamt,wohngeb_1,wohngeb_2,wohngeb_3,wohnheime,wohnfläche,wohn_insgesamt,wohn_1raum,wohn_2raum,wohn_3raum,wohn_4raum,wohn_5raum,wohn_6raum,wohn_7raum,wohn_gr7raum
0,DG,DG000000,Deutschland,19053216.0,12707978.0,3129233.0,3193736.0,22269.0,3753715.0,42235402.0,1432013.0,3921635.0,9180006.0,10694196.0,7158060.0,4662194.0,5187298.0,42135675.0
1,1,01000000,Schleswig-Holstein,820540.0,647342.0,80399.0,92110.0,689.0,134987.2,1489901.0,38233.0,132396.0,304865.0,355232.0,294106.0,187265.0,177804.0,1424144.0
2,1001,01001000,Flensburg,17208.0,11449.0,961.0,4754.0,44.0,3877.4,50432.0,2726.0,6087.0,14512.0,13123.0,7215.0,3455.0,3314.0,26634.0
3,1002,01002000,Kiel,37217.0,22805.0,2246.0,12051.0,115.0,9487.1,134831.0,7474.0,18285.0,41434.0,34492.0,18758.0,8170.0,6218.0,50580.0
4,1003,01003000,Lübeck,43473.0,28778.0,4069.0,10591.0,35.0,8552.6,117615.0,5370.0,15214.0,31360.0,32490.0,18406.0,8567.0,6208.0,49297.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13903,16077049,16077049,Vollmershain,105.0,78.0,20.0,7.0,NaN,14.8,146.0,3.0,6.0,19.0,23.0,41.0,24.0,30.0,233.0
13904,16077051,16077051,Wildenbörten,114.0,88.0,21.0,5.0,NaN,14.1,149.0,1.0,3.0,16.0,31.0,50.0,22.0,26.0,210.0
13905,16077052,16077052,Windischleuba,630.0,458.0,102.0,70.0,NaN,94.3,1033.0,10.0,46.0,180.0,289.0,220.0,150.0,138.0,1104.0
13906,16077055,16077055,Ziegelheim,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13907,16077056,16077056,Saara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
def get_wohnung(inVal,output,inputType='ags'):
    pop=Wohnungen[Wohnungen[inputType]==inVal][output]
    return pop.values[0]

In [182]:
get_wohnung('01001000','wohnfläche')

3877.4

In [17]:
Wohnungen[Wohnungen['ags']=='0FALSCH']

,id,ags,gem,wohngeb_insgesamt,wohngeb_1,wohngeb_2,wohngeb_3,wohnheime,wohnfläche,wohn_insgesamt,wohn_1raum,wohn_2raum,wohn_3raum,wohn_4raum,wohn_5raum,wohn_6raum,wohn_7raum,wohn_gr7raum
1143,31,0FALSCH,"Braunschweig, Stat. Region",413273.0,281271.0,68242.0,63173.0,587.0,78430.6,842376.0,27396.0,48207.0,145993.0,228619.0,163277.0,101325.0,127559.0,1047815.0
1403,32,0FALSCH,"Hannover, Stat. Region",517239.0,349677.0,86046.0,81039.0,477.0,103224.8,1100175.0,32301.0,64143.0,212406.0,302504.0,202743.0,129975.0,156103.0,1278384.0
1647,33,0FALSCH,"Lüneburg, Stat. Region",545520.0,430367.0,71936.0,42804.0,413.0,87521.6,843170.0,14305.0,46309.0,124727.0,186362.0,180313.0,129617.0,161537.0,1322044.0
2036,34,0FALSCH,"Weser-Ems, Stat. Region",774178.0,607575.0,102221.0,63567.0,815.0,126683.0,1213535.0,20126.0,59757.0,173523.0,248085.0,238918.0,189755.0,283371.0,2330436.0
2304,51,0FALSCH,"Düsseldorf, Regierungsbezirk",1011351.0,603571.0,136692.0,269998.0,1090.0,222819.6,2686576.0,86947.0,326695.0,717580.0,730953.0,394736.0,226526.0,203139.0,1633841.0
2376,53,0FALSCH,"Köln, Regierungsbezirk",998247.0,687417.0,131337.0,178246.0,1247.0,196906.2,2214642.0,101707.0,242473.0,500393.0,529994.0,355915.0,243881.0,240279.0,1935231.0
2494,55,0FALSCH,"Münster, Regierungsbezirk",613787.0,397257.0,110437.0,105324.0,769.0,116577.4,1272346.0,30066.0,101251.0,261491.0,327162.0,226210.0,154119.0,172047.0,1401109.0
2578,57,0FALSCH,"Detmold, Regierungsbezirk",503363.0,311236.0,114885.0,76641.0,601.0,94816.6,992258.0,22247.0,67649.0,180479.0,248963.0,190616.0,129039.0,153265.0,1251329.0
2655,59,0FALSCH,"Arnsberg, Regierungsbezirk",756803.0,419389.0,156276.0,180315.0,823.0,158485.4,1848541.0,41034.0,175276.0,453564.0,510570.0,295345.0,178046.0,194706.0,1585882.0
2747,64,0FALSCH,"Darmstadt, Regierungsbezirk",784470.0,471456.0,151537.0,159402.0,2075.0,173461.6,1929362.0,73688.0,188351.0,431164.0,499094.0,309893.0,196539.0,230633.0,1869365.0
2948,65,0FALSCH,"Gießen, Regierungsbezirk",283084.0,187921.0,63997.0,30639.0,527.0,51147.0,504356.0,15918.0,30609.0,80519.0,104541.0,89557.0,73124.0,110088.0,912089.0
3055,66,0FALSCH,"Kassel, Regierungsbezirk",325765.0,204476.0,79069.0,41261.0,959.0,59561.1,607687.0,12327.0,40464.0,102671.0,143170.0,115119.0,80577.0,113359.0,936684.0
3204,71,0FALSCH,"Koblenz, Stat. Region",463608.0,338683.0,76260.0,48347.0,318.0,78362.4,762503.0,13382.0,43786.0,119727.0,161439.0,140317.0,119455.0,164397.0,1347909.0
4327,72,0FALSCH,"Trier, Stat. Region",169559.0,126367.0,26438.0,16621.0,133.0,28995.8,281443.0,9816.0,16455.0,38827.0,53859.0,49702.0,45482.0,67302.0,554058.0
4888,73,0FALSCH,"Rheinhessen-Pfalz, Stat. Region",554627.0,400588.0,84962.0,68450.0,627.0,103749.8,1058200.0,38804.0,77888.0,190071.0,235669.0,190479.0,146212.0,179077.0,1457400.0
5537,81,0FALSCH,"Stuttgart, Regierungsbezirk",878823.0,527277.0,183325.0,166947.0,1274.0,177956.4,1965137.0,62105.0,157156.0,381553.0,520806.0,360351.0,230703.0,252463.0,2030095.0
5892,82,0FALSCH,"Karlsruhe, Regierungsbezirk",602226.0,361685.0,126962.0,112709.0,870.0,127065.3,1372040.0,56044.0,122585.0,282522.0,347786.0,233432.0,153769.0,175902.0,1418239.0
6111,83,0FALSCH,"Freiburg, Regierungsbezirk",487289.0,284260.0,111417.0,90957.0,655.0,101851.0,1089599.0,38473.0,89348.0,199334.0,283315.0,202009.0,129960.0,147160.0,1186068.0
6425,84,0FALSCH,"Tübingen, Regierungsbezirk",459840.0,312514.0,86812.0,59824.0,690.0,84173.1,871155.0,26428.0,65189.0,142279.0,194426.0,164933.0,124838.0,153062.0,1237969.0
6691,91,0FALSCH,"Oberbayern, Regierungsbezirk",914566.0,608674.0,142614.0,162238.0,1040.0,204756.0,2304083.0,151342.0,297024.0,501042.0,499697.0,338679.0,239755.0,276544.0,2257395.0
7242,92,0FALSCH,"Niederbayern, Regierungsbezirk",356837.0,265337.0,63081.0,28110.0,309.0,62013.7,580889.0,17157.0,37042.0,82399.0,107440.0,103251.0,93279.0,140321.0,1169427.0
7527,93,0FALSCH,"Oberpfalz, Regierungsbezirk",299789.0,198363.0,68019.0,33131.0,276.0,54868.7,549521.0,19809.0,35227.0,86814.0,118268.0,107282.0,80486.0,101635.0,839665.0
7773,94,0FALSCH,"Oberfranken, Regierungsbezirk",291556.0,189094.0,64112.0,38014.0,336.0,52461.8,546761.0,17965.0,33005.0,90205.0,124940.0,103084.0,76713.0,100849.0,834379.0
8048,95,0FALSCH,"Mittelfranken, Regierungsbezirk",394342.0,263326.0,66480.0,63977.0,559.0,80839.8,885790.0,36962.0,72362.0,180953.0,225488.0,146667.0,104136.0,119222.0,973772.0
8302,96,0FALSCH,"Unterfranken, Regierungsbezirk",350298.0,219209.0,86735.0,43980.0,374.0,64624.1,657357.0,18146.0,41705.0,109274.0,155700.0,123072.0,91738.0,117722.0,962208.0
8679,97,0FALSCH,"Schwaben, Regierungsbezirk",456696.0,323997.0,71680.0,60490.0,529.0,86012.8,905891.0,29664.0,72641.0,167974.0,200753.0,163842.0,126670.0,144347.0,1167869.0
11248,141,0FALSCH,"Chemnitz, Regierungsbezirk",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11261,142,0FALSCH,"Dresden, Regierungsbezirk",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11273,143,0FALSCH,"Leipzig, Regierungsbezirk",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11280,145,0FALSCH,"Chemnitz, Stat. Region",321334.0,178808.0,63052.0,79320.0,154.0,62400.1,871340.0,24113.0,89017.0,250419.0,260456.0,129354.0,66974.0,51007.0,402704.0
11504,146,0FALSCH,"Dresden, Stat. Region",320614.0,199514.0,48689.0,72180.0,231.0,66981.3,899765.0,30731.0,90065.0,243081.0,270193.0,136256.0,73963.0,55476.0,438607.0
11716,147,0FALSCH,"Leipzig, Stat. Region",184346.0,117353.0,20109.0,46766.0,118.0,43657.0,593304.0,21679.0,68221.0,171999.0,177617.0,84282.0,39692.0,29814.0,236009.0
12866,151,0FALSCH,"Dessau, Stat. Region",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12873,152,0FALSCH,"Halle, Stat. Region",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12881,153,0FALSCH,"Magdeburg, Stat. Region",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Einwohner

noch Probleme mit den Datentypen ... alles was als int gecastest wird, wird zu float ?

In [9]:
#import Einwohner

renameDict={'8-stellige AGS':'ags','Einheit':'gem','Zahl':'id','Insgesamt':'total','männlich':'male','weiblich':'female'}
Einwohner = pd.read_csv('data/Einwohner.csv',sep=';',header=5,encoding="utf8")

#drop empty column
Einwohner.drop(columns=["Unnamed: 5"],inplace=True)

Einwohner.rename(columns=renameDict,inplace=True)
#put ags as second column
Einwohner=Einwohner[['id','ags',"gem",'total','female','male']]

#drop last 12 columns which are comments

Einwohner.drop([i+13908 for i in range(33)],axis=0,inplace=True)

#change cell types to string, int or float defined as in dtypes dict

#workaround for missing values replace all '-' and '.' with -1 
Einwohner.replace('-',-1,inplace=True)
Einwohner.replace('.',-1,inplace=True)
    

dtypesDict={'id':'str','ags':'str','gem':'str','total':'int','female':'int','male':'int'}
    
#change data types
for key in dtypesDict:
    Einwohner[key]=Einwohner[key].astype(dtypesDict[key])
    
    
#and replace all -1 with NaN   
Einwohner.replace(-1,np.NaN,inplace=True)

#make ags column 8 digits
#for i in range(len(Wohnungen['ags'])):
#    if len(Wohnungen.iat[i,1]) < 8 :
#        Wohnungen.iat[i,1]= '0'+ Wohnungen.iat[i,1]

#print(Einwohner.dtypes)  

display(Einwohner)
Einwohner.to_pickle('data/Einwohner.pki')

,id,ags,gem,total,female,male
0,DG,DG000000,Deutschland,83019213.0,42052522.0,40966691.0
1,1,01000000,Schleswig-Holstein,2896712.0,1477255.0,1419457.0
2,1001,01001000,Flensburg,89504.0,44905.0,44599.0
3,1002,01002000,Kiel,247548.0,126982.0,120566.0
4,1003,01003000,Lübeck,217198.0,112827.0,104371.0
...,...,...,...,...,...,...
13903,16077049,16077049,Vollmershain,317.0,163.0,154.0
13904,16077051,16077051,Wildenbörten,252.0,121.0,131.0
13905,16077052,16077052,Windischleuba,1925.0,969.0,956.0
13906,16077055,16077055,Ziegelheim,NaN,NaN,NaN
13907,16077056,16077056,Saara,NaN,NaN,NaN

In [78]:
def get_einwohner(inVal,output,inputType='ags'):
    pop=Einwohner[Einwohner[inputType]==inVal][output]
    return pop.values[0]

In [90]:
get_einwohner('01002000','total')

247548.0